#ifndef GAMEUIDEFINES_H_INCLUDED
#define GAMEUIDEFINES_H_INCLUDED

#define MAZEBORDER_WIDTH 176
#define MAZEBORDER_HEIGHT 125

#define MAZECOMPASS_STARTX 0
#define MAZECOMPASS_STARTY 24
#define MAZECOMPASS_WIDTH 43
#define MAZECOMPASS_HEIGHT 14

#define MAPWINC_STARTX 30
#define MAPWINC_STARTY 9
#define MAPWINC_WIDTH 9
#define MAPWINC_HEIGHT 9

#define MAPWINS_STARTX 30
#define MAPWINS_STARTY 21
#define MAPWINS_WIDTH 2
#define MAPWINS_HEIGHT 2

#define MAZEBORDER_H 24
#define MAZEBORDER_V 17

#define CHARWIN_WIDTH 68
#define CHARWIN_HEIGHT 97

#define CHARBACK_STARTX 44
#define CHARBACK_STARTY 25
#define CHARBACK_WIDTH 4
#define CHARBACK_HEIGHT 4

#define CHARWINTC_STARTX 0
#define CHARWINTC_STARTY 9
#define CHARWINBC_STARTX 15
#define CHARWINBC_STARTY 9
#define CHARWINC_WIDTH 14
#define CHARWINC_HEIGHT 14

#define CHAR_HEART_STARTX 64
#define CHAR_HEART_STARTY 9
#define CHAR_HEART_WIDTH 15
#define CHAR_HEART_HEIGHT 14

#define CHAR_MIND_STARTX 48
#define CHAR_MIND_STARTY 9
#define CHAR_MIND_WIDTH 15
#define CHAR_MIND_HEIGHT 14

#define PORT_WIDTH 48
#define PORT_HEIGHT 48

#define DIGIT_STARTX 0
#define DIGIT_STARTY 0
#define DIGIT_WIDTH 6
#define DIGIT_HEIGHT 8

#define NAV_WIDTH 18
#define NAV_HEIGHT 18

#define MINIMAP_X 133
#define MINIMAP_Y 137

#define BUTTON_ROTLEFT_X 74
#define BUTTON_ROTLEFT_Y 137
#define BUTTON_FORWARD_X 92
#define BUTTON_FORWARD_Y 137
#define BUTTON_ROTRIGHT_X 110
#define BUTTON_ROTRIGHT_Y 137

#define BUTTON_LEFT_X 74
#define BUTTON_LEFT_Y 155
#define BUTTON_BACKWARD_X 92
#define BUTTON_BACKWARD_Y 155
#define BUTTON_RIGHT_X 110
#define BUTTON_RIGHT_Y 155

#define BUTTON_CHARACTER_X 192
#define BUTTON_CHARACTER_Y 137
#define BUTTON_MAGIC_X 210
#define BUTTON_MAGIC_Y 137
#define BUTTON_INVENTORY_X 228
#define BUTTON_INVENTORY_Y 137

#define BUTTON_CONFIG_X 192
#define BUTTON_CONFIG_Y 175
#define BUTTON_SAVE_X 210
#define BUTTON_SAVE_Y 175
#define BUTTON_LOAD_X 228
#define BUTTON_LOAD_Y 175

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 200

#define NAV_SHEET_Y 38
#define NAV_SHEET_X 0

#define USER_SHEET_Y 56
#define USER_SHEET_X 0

#define MAZE_BACKGROUND_X 81
#define MAZE_BACKGROUND_Y 0
#define MAZE_BACKGROUND_WIDTH 32
#define MAZE_BACKGROUND_HEIGHT 32

#define CARDINAL_X 51
#define CARDINAL_Y 26
#define CARDINAL_WIDTH 7
#define CARDINAL_HEIGHT 6

#define ARROW_X 73
#define ARROW_Y 23
#define ARROW_WIDTH 8
#define ARROW_HEIGHT 8

#endif// GAMEUIDEFINES_H_INCLUDED
