#ifndef MAZEDEFINES_H
#define MAZEDEFINES_H

typedef enum 
{
    FORWARDD_LEFT3, FORWARDD_LEFT2, FORWARDD_LEFT1, FORWARDD_CENTER, FORWARDD_RIGHT1, FORWARDD_RIGHT2, FORWARDD_RIGHT3,
    FARSIDED2_LEFT1, FARSIDED1_LEFT1, SIDED_LEFT1, SIDED_RIGHT1, FARSIDED1_RIGHT1, FARSIDED2_RIGHT1,
    FORWARDC_LEFT2, FORWARDC_LEFT1, FORWARDC_CENTER, FORWARDC_RIGHT1, FORWARDC_RIGHT2,
    FARSIDEC_LEFT1, SIDEC_LEFT1, SIDEC_RIGHT1, FARSIDEC_RIGHT1,
    FORWARDB_LEFT1, FORWARDB_CENTER, FORWARDB_RIGHT1,
    SIDEB_LEFT1, SIDEB_RIGHT1,
    FORWARDA_LEFT1, FORWARDA_CENTER, FORWARDA_RIGHT1,
    SIDEA_LEFT1, SIDEA_RIGHT1
} WallPartId;

#define MAZEVIEW_X 72
#define MAZEVIEW_Y 8
#define MAZEVIEW_WIDTH 176
#define MAZEVIEW_HEIGHT 120

#endif // MAZEDEFINES_H
